---
# task for sentry.sentry

- name: Install packages via pip sentry
  become: true
  pip: name="{{ item.name }}" version="{{ item.version }}"
  when: _sentry_pip_dependencies is defined
  with_items: "{{ _sentry_pip_dependencies | default({}) }}"
