# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up
version: '3'
services:

  web:
    restart: always
    image: ansible-role-sentry
    environment: &environment
      - DEBUG=True
    build:
      context: .
      dockerfile: provision/docker/web/Dockerfile
    env_file:
      - .env
